--------------------------------------------------------
-- Archivo creado  - martes-abril-14-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CAMISETA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."CAMISETA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CARRITO_COMPRAS_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."CARRITO_COMPRAS_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COLOR_CAMISETA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."COLOR_CAMISETA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ESTAMPA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."ESTAMPA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MATERIAL_CAMISETA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."MATERIAL_CAMISETA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence METODO_ENVIO_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."METODO_ENVIO_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence METODO_PAGO_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."METODO_PAGO_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERSONA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."PERSONA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRIVILEGIO_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."PRIVILEGIO_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RED_SOCIAL_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."RED_SOCIAL_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROL_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."ROL_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROL_PRIVILEGIO_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."ROL_PRIVILEGIO_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TALLA_CAMISETA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."TALLA_CAMISETA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAMANO_ESTAMPADO_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."TAMANO_ESTAMPADO_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TEMA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."TEMA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_CAMISETA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."TIPO_CAMISETA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence UBICACION_ESTAM_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."UBICACION_ESTAM_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."USUARIO_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_REDSOCIAL_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."USUARIO_REDSOCIAL_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VENTA_ID_GENERATOR
--------------------------------------------------------

   CREATE SEQUENCE  "ESTAMPATE_DB"."VENTA_ID_GENERATOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CAMISETA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."CAMISETA" 
   (	"ID" NUMBER(8,2), 
	"ESTAMPA" NUMBER(8,2), 
	"TALLA" NUMBER(8,2), 
	"COLOR" NUMBER(8,2), 
	"MATERIAL" NUMBER(8,2), 
	"UBICACION_ESTAMPADO" NUMBER(8,2), 
	"TAMANO_ESTAMPADO" NUMBER(8,2), 
	"TEXTO" VARCHAR2(100 BYTE), 
	"CARRITO" NUMBER(8,2), 
	"PRECIO" NUMBER(8,2), 
	"TIPO_CAMISETA" NUMBER(8,2), 
	"CANTIDAD" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CARRITO_COMPRAS
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."CARRITO_COMPRAS" 
   (	"ID" NUMBER(8,2), 
	"USUARIO" NUMBER(8,2), 
	"VALOR_TOTAL" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLOR_CAMISETA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."COLOR_CAMISETA" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CODIGO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTAMPA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."ESTAMPA" 
   (	"ID" NUMBER(8,2), 
	"INFORMACION" VARCHAR2(100 BYTE), 
	"IMAGEN" VARCHAR2(50 BYTE), 
	"PRECIO" NUMBER(8,2), 
	"TEMA" NUMBER(8,2), 
	"USUARIO" NUMBER(8,2), 
	"RATTING" NUMBER(8,2), 
	"CANTIDAD_VOTOS" NUMBER(8,2), 
	"POPULARIDAD" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIAL_CAMISETA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."MATERIAL_CAMISETA" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table METODO_ENVIO
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."METODO_ENVIO" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"VALOR" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table METODO_PAGO
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."METODO_PAGO" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."PERSONA" 
   (	"ID" NUMBER(8,2), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"MUNICIPIO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DEPARTAMENTO" VARCHAR2(50 BYTE), 
	"PAIS" VARCHAR2(50 BYTE), 
	"IDENTIFICACION" VARCHAR2(50 BYTE), 
	"FECHA_NACIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRIVILEGIO
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."PRIVILEGIO" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"FUNCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RED_SOCIAL
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."RED_SOCIAL" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."ROL" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROL_PRIVILEGIO
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."ROL_PRIVILEGIO" 
   (	"ID" NUMBER(8,2), 
	"ID_ROL" NUMBER(8,2), 
	"ID_PRIVILEGIO" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TALLA_CAMISETA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."TALLA_CAMISETA" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAMANO_ESTAMPADO
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."TAMANO_ESTAMPADO" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEMA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."TEMA" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_CAMISETA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."TIPO_CAMISETA" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"UBICACION" VARCHAR2(500 BYTE), 
	"VALOR" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UBICACION_ESTAMPADO
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."UBICACION_ESTAMPADO" 
   (	"ID" NUMBER(8,2), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."USUARIO" 
   (	"ID" NUMBER(8,2), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"PERSONA" NUMBER(8,2), 
	"RATTING" NUMBER(8,2), 
	"CANTIDAD_VOTOS" NUMBER(8,2), 
	"ROL" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO_REDSOCIAL
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."USUARIO_REDSOCIAL" 
   (	"ID" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"ID_REDSOCIAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "ESTAMPATE_DB"."VENTA" 
   (	"ID" NUMBER(8,2), 
	"METODO_ENVIO" NUMBER(8,2), 
	"METODO_PAGO" NUMBER(8,2), 
	"FECHA" DATE, 
	"CARRITO" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ESTAMPATE_DB.CAMISETA
SET DEFINE OFF;
REM INSERTING into ESTAMPATE_DB.CARRITO_COMPRAS
SET DEFINE OFF;
REM INSERTING into ESTAMPATE_DB.COLOR_CAMISETA
SET DEFINE OFF;
Insert into ESTAMPATE_DB.COLOR_CAMISETA (ID,NOMBRE,CODIGO) values ('1','ROJO','#D9534F');
Insert into ESTAMPATE_DB.COLOR_CAMISETA (ID,NOMBRE,CODIGO) values ('2','VERDE','#5CB85C');
Insert into ESTAMPATE_DB.COLOR_CAMISETA (ID,NOMBRE,CODIGO) values ('3','AZUL CLARITO','#5BC0DE');
Insert into ESTAMPATE_DB.COLOR_CAMISETA (ID,NOMBRE,CODIGO) values ('4','AZUL','#428BCA');
Insert into ESTAMPATE_DB.COLOR_CAMISETA (ID,NOMBRE,CODIGO) values ('5','NARANJA','#F0AD4E');
Insert into ESTAMPATE_DB.COLOR_CAMISETA (ID,NOMBRE,CODIGO) values ('6','BLANCO','#E3E3E3');
REM INSERTING into ESTAMPATE_DB.ESTAMPA
SET DEFINE OFF;
Insert into ESTAMPATE_DB.ESTAMPA (ID,INFORMACION,IMAGEN,PRECIO,TEMA,USUARIO,RATTING,CANTIDAD_VOTOS,POPULARIDAD,NOMBRE) values ('1','Información Paisaje 1','http://pinegrow.com/placeholders/img4.jpg','10000','1','1','0','0','0','Paisaje 1');
Insert into ESTAMPATE_DB.ESTAMPA (ID,INFORMACION,IMAGEN,PRECIO,TEMA,USUARIO,RATTING,CANTIDAD_VOTOS,POPULARIDAD,NOMBRE) values ('2','Información  Paisaje 2','http://pinegrow.com/placeholders/img3.jpg','5000','1','1','0','0','0','Paisaje 2');
Insert into ESTAMPATE_DB.ESTAMPA (ID,INFORMACION,IMAGEN,PRECIO,TEMA,USUARIO,RATTING,CANTIDAD_VOTOS,POPULARIDAD,NOMBRE) values ('3','Información Paisaje 3','http://pinegrow.com/placeholders/img8.jpg','6000','1','1','0','0','0','Paisaje 3');
Insert into ESTAMPATE_DB.ESTAMPA (ID,INFORMACION,IMAGEN,PRECIO,TEMA,USUARIO,RATTING,CANTIDAD_VOTOS,POPULARIDAD,NOMBRE) values ('4','Información Paisaje 4','http://pinegrow.com/placeholders/img6.jpg','7000','1','1','0','0','0','Paisaje 4');
REM INSERTING into ESTAMPATE_DB.MATERIAL_CAMISETA
SET DEFINE OFF;
Insert into ESTAMPATE_DB.MATERIAL_CAMISETA (ID,NOMBRE) values ('1','100% Algodon');
REM INSERTING into ESTAMPATE_DB.METODO_ENVIO
SET DEFINE OFF;
Insert into ESTAMPATE_DB.METODO_ENVIO (ID,NOMBRE,VALOR) values ('1','Nacional','10000');
Insert into ESTAMPATE_DB.METODO_ENVIO (ID,NOMBRE,VALOR) values ('2','Internacional','20000');
REM INSERTING into ESTAMPATE_DB.METODO_PAGO
SET DEFINE OFF;
REM INSERTING into ESTAMPATE_DB.PERSONA
SET DEFINE OFF;
Insert into ESTAMPATE_DB.PERSONA (ID,NOMBRES,APELLIDOS,TELEFONO,DIRECCION,MUNICIPIO,EMAIL,DEPARTAMENTO,PAIS,IDENTIFICACION,FECHA_NACIMIENTO) values ('1','Listman','Gamboa','3203856833','Carrera 77# 52a-67','Pamplona','lm.gamboa10@uninades.edu.co','Norte de Santander','Colombia','1094266902',to_date('23/01/90','DD/MM/RR'));
REM INSERTING into ESTAMPATE_DB.PRIVILEGIO
SET DEFINE OFF;
Insert into ESTAMPATE_DB.PRIVILEGIO (ID,NOMBRE,URL,FUNCION) values ('1','Catalogo Camisetas','/catalogo',null);
Insert into ESTAMPATE_DB.PRIVILEGIO (ID,NOMBRE,URL,FUNCION) values ('2','Estampa','/estampateWEB/estampa',null);
Insert into ESTAMPATE_DB.PRIVILEGIO (ID,NOMBRE,URL,FUNCION) values ('3','Administracion Estampa','/estampateWEB/estampaAdmin',null);
Insert into ESTAMPATE_DB.PRIVILEGIO (ID,NOMBRE,URL,FUNCION) values ('5','Perfil','/estampateWEB/perfil',null);
Insert into ESTAMPATE_DB.PRIVILEGIO (ID,NOMBRE,URL,FUNCION) values ('4','Camisetas','/estampateWEB/camisetasAdmin',null);
REM INSERTING into ESTAMPATE_DB.RED_SOCIAL
SET DEFINE OFF;
REM INSERTING into ESTAMPATE_DB.ROL
SET DEFINE OFF;
Insert into ESTAMPATE_DB.ROL (ID,NOMBRE) values ('1','admin');
Insert into ESTAMPATE_DB.ROL (ID,NOMBRE) values ('2','artista');
Insert into ESTAMPATE_DB.ROL (ID,NOMBRE) values ('3','comprador');
REM INSERTING into ESTAMPATE_DB.ROL_PRIVILEGIO
SET DEFINE OFF;
Insert into ESTAMPATE_DB.ROL_PRIVILEGIO (ID,ID_ROL,ID_PRIVILEGIO) values ('1','1','1');
Insert into ESTAMPATE_DB.ROL_PRIVILEGIO (ID,ID_ROL,ID_PRIVILEGIO) values ('2','1','2');
Insert into ESTAMPATE_DB.ROL_PRIVILEGIO (ID,ID_ROL,ID_PRIVILEGIO) values ('3','1','3');
Insert into ESTAMPATE_DB.ROL_PRIVILEGIO (ID,ID_ROL,ID_PRIVILEGIO) values ('4','1','4');
Insert into ESTAMPATE_DB.ROL_PRIVILEGIO (ID,ID_ROL,ID_PRIVILEGIO) values ('5','1','5');
REM INSERTING into ESTAMPATE_DB.TALLA_CAMISETA
SET DEFINE OFF;
Insert into ESTAMPATE_DB.TALLA_CAMISETA (ID,NOMBRE) values ('1','XS');
Insert into ESTAMPATE_DB.TALLA_CAMISETA (ID,NOMBRE) values ('2','S');
Insert into ESTAMPATE_DB.TALLA_CAMISETA (ID,NOMBRE) values ('3','M');
Insert into ESTAMPATE_DB.TALLA_CAMISETA (ID,NOMBRE) values ('4','L');
Insert into ESTAMPATE_DB.TALLA_CAMISETA (ID,NOMBRE) values ('5','XL');
REM INSERTING into ESTAMPATE_DB.TAMANO_ESTAMPADO
SET DEFINE OFF;
REM INSERTING into ESTAMPATE_DB.TEMA
SET DEFINE OFF;
Insert into ESTAMPATE_DB.TEMA (ID,NOMBRE) values ('1','General');
REM INSERTING into ESTAMPATE_DB.TIPO_CAMISETA
SET DEFINE OFF;
Insert into ESTAMPATE_DB.TIPO_CAMISETA (ID,NOMBRE,UBICACION,VALOR) values ('1','Cuello en V','http://www.siman.com/media/catalog/product/cache/1/image/920x/9df78eab33525d08d6e5fb8d27136e95/4/9/490395300043.jpg','10000');
Insert into ESTAMPATE_DB.TIPO_CAMISETA (ID,NOMBRE,UBICACION,VALOR) values ('2','Camiseta Polo','http://www.jpsalesusa.com/images/polo/2800/g280_00_p.jpg','25000');
Insert into ESTAMPATE_DB.TIPO_CAMISETA (ID,NOMBRE,UBICACION,VALOR) values ('3','Cuello Redondo','http://www.textilesjb.com/catalogo/images/D/2crh-01Bco.jpg','30000');
Insert into ESTAMPATE_DB.TIPO_CAMISETA (ID,NOMBRE,UBICACION,VALOR) values ('4','Camiseta Femenina','http://t-shirtfemale.net/wp-content/uploads/2015/03/black-woman-in-white-t-shirt-okbbbotp.jpg','40000');
REM INSERTING into ESTAMPATE_DB.UBICACION_ESTAMPADO
SET DEFINE OFF;
REM INSERTING into ESTAMPATE_DB.USUARIO
SET DEFINE OFF;
Insert into ESTAMPATE_DB.USUARIO (ID,USERNAME,PASSWORD,PERSONA,RATTING,CANTIDAD_VOTOS,ROL) values ('1','listman','listman','1','0','0','1');
REM INSERTING into ESTAMPATE_DB.USUARIO_REDSOCIAL
SET DEFINE OFF;
REM INSERTING into ESTAMPATE_DB.VENTA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ESTAMPA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_ESTAMPA" ON "ESTAMPATE_DB"."ESTAMPA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CAMISETA_COLOR_CAMISETA
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CAMISETA_COLOR_CAMISETA" ON "ESTAMPATE_DB"."CAMISETA" ("COLOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_ESTAMPA_USUARIO
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_ESTAMPA_USUARIO" ON "ESTAMPATE_DB"."ESTAMPA" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_VENTA_CARRITO_COMPRAS
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_VENTA_CARRITO_COMPRAS" ON "ESTAMPATE_DB"."VENTA" ("CARRITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_METODO_ENVIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_METODO_ENVIO" ON "ESTAMPATE_DB"."METODO_ENVIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_ESTAMPA_TEMA
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_ESTAMPA_TEMA" ON "ESTAMPATE_DB"."ESTAMPA" ("TEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CAMISETA_ESTAMPA
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CAMISETA_ESTAMPA" ON "ESTAMPATE_DB"."CAMISETA" ("ESTAMPA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIO_REDSOCIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."USUARIO_REDSOCIAL_PK" ON "ESTAMPATE_DB"."USUARIO_REDSOCIAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CAMISETA_TAMANO_ESTAMPADO
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CAMISETA_TAMANO_ESTAMPADO" ON "ESTAMPATE_DB"."CAMISETA" ("TAMANO_ESTAMPADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TEMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_TEMA" ON "ESTAMPATE_DB"."TEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CARRITO_COMPRAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_CARRITO_COMPRAS" ON "ESTAMPATE_DB"."CARRITO_COMPRAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CAMISETA_UBICACION_E01
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CAMISETA_UBICACION_E01" ON "ESTAMPATE_DB"."CAMISETA" ("UBICACION_ESTAMPADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_ROL_PRIVILEGIO_ROL
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_ROL_PRIVILEGIO_ROL" ON "ESTAMPATE_DB"."ROL_PRIVILEGIO" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_VENTA_METODO_ENVIO
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_VENTA_METODO_ENVIO" ON "ESTAMPATE_DB"."VENTA" ("METODO_ENVIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MATERIAL_CAMISETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_MATERIAL_CAMISETA" ON "ESTAMPATE_DB"."MATERIAL_CAMISETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_UBICACION_ESTAMPADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_UBICACION_ESTAMPADO" ON "ESTAMPATE_DB"."UBICACION_ESTAMPADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_ROL" ON "ESTAMPATE_DB"."ROL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_METODO_PAGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_METODO_PAGO" ON "ESTAMPATE_DB"."METODO_PAGO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CAMISETA_CARRITO_COMPRAS
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CAMISETA_CARRITO_COMPRAS" ON "ESTAMPATE_DB"."CAMISETA" ("CARRITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CAMISETA_TALLA_CAMISETA
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CAMISETA_TALLA_CAMISETA" ON "ESTAMPATE_DB"."CAMISETA" ("TALLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PRIVILEGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_PRIVILEGIO" ON "ESTAMPATE_DB"."PRIVILEGIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PERSONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_PERSONA" ON "ESTAMPATE_DB"."PERSONA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CARRITO_COMPRAS_USUARIO
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CARRITO_COMPRAS_USUARIO" ON "ESTAMPATE_DB"."CARRITO_COMPRAS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_USUARIO" ON "ESTAMPATE_DB"."USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_CAMISETA_MATERIAL_CA01
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_CAMISETA_MATERIAL_CA01" ON "ESTAMPATE_DB"."CAMISETA" ("MATERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_ROL_PRIVILEGIO_PRIVILEGIO
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_ROL_PRIVILEGIO_PRIVILEGIO" ON "ESTAMPATE_DB"."ROL_PRIVILEGIO" ("ID_PRIVILEGIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TALLA_CAMISETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_TALLA_CAMISETA" ON "ESTAMPATE_DB"."TALLA_CAMISETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ROL_PRIVILEGIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_ROL_PRIVILEGIO" ON "ESTAMPATE_DB"."ROL_PRIVILEGIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CAMISETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_CAMISETA" ON "ESTAMPATE_DB"."CAMISETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_USUARIO_PERSONA
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_USUARIO_PERSONA" ON "ESTAMPATE_DB"."USUARIO" ("PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TAMANO_ESTAMPADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_TAMANO_ESTAMPADO" ON "ESTAMPATE_DB"."TAMANO_ESTAMPADO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IXFK_VENTA_METODO_PAGO
--------------------------------------------------------

  CREATE INDEX "ESTAMPATE_DB"."IXFK_VENTA_METODO_PAGO" ON "ESTAMPATE_DB"."VENTA" ("METODO_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_COLOR_CAMISETA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_COLOR_CAMISETA" ON "ESTAMPATE_DB"."COLOR_CAMISETA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_VENTA" ON "ESTAMPATE_DB"."VENTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_RED_SOCIAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESTAMPATE_DB"."PK_RED_SOCIAL" ON "ESTAMPATE_DB"."RED_SOCIAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."VENTA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."VENTA" MODIFY ("METODO_ENVIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."VENTA" MODIFY ("METODO_PAGO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."VENTA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."VENTA" MODIFY ("CARRITO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."VENTA" ADD CONSTRAINT "PK_VENTA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("PAIS" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PERSONA" ADD CONSTRAINT "PK_PERSONA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRIVILEGIO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."PRIVILEGIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PRIVILEGIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."PRIVILEGIO" ADD CONSTRAINT "PK_PRIVILEGIO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RED_SOCIAL
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."RED_SOCIAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."RED_SOCIAL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."RED_SOCIAL" ADD CONSTRAINT "PK_RED_SOCIAL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIAL_CAMISETA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."MATERIAL_CAMISETA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."MATERIAL_CAMISETA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."MATERIAL_CAMISETA" ADD CONSTRAINT "PK_MATERIAL_CAMISETA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAMISETA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("TIPO_CAMISETA" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("ESTAMPA" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("TALLA" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("CARRITO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "PK_CAMISETA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARRITO_COMPRAS
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."CARRITO_COMPRAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CARRITO_COMPRAS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CARRITO_COMPRAS" MODIFY ("VALOR_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."CARRITO_COMPRAS" ADD CONSTRAINT "PK_CARRITO_COMPRAS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTAMPA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" MODIFY ("INFORMACION" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" MODIFY ("IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" MODIFY ("TEMA" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" ADD CONSTRAINT "PK_ESTAMPA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COLOR_CAMISETA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."COLOR_CAMISETA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."COLOR_CAMISETA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."COLOR_CAMISETA" ADD CONSTRAINT "PK_COLOR_CAMISETA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEMA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."TEMA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TEMA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TEMA" ADD CONSTRAINT "PK_TEMA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."ROL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ROL" ADD CONSTRAINT "PK_ROL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_CAMISETA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."TIPO_CAMISETA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."TIPO_CAMISETA" MODIFY ("UBICACION" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TIPO_CAMISETA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TIPO_CAMISETA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL_PRIVILEGIO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."ROL_PRIVILEGIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ROL_PRIVILEGIO" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ROL_PRIVILEGIO" MODIFY ("ID_PRIVILEGIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."ROL_PRIVILEGIO" ADD CONSTRAINT "PK_ROL_PRIVILEGIO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO_REDSOCIAL
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."USUARIO_REDSOCIAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."USUARIO_REDSOCIAL" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."USUARIO_REDSOCIAL" MODIFY ("ID_REDSOCIAL" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."USUARIO_REDSOCIAL" ADD CONSTRAINT "USUARIO_REDSOCIAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UBICACION_ESTAMPADO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."UBICACION_ESTAMPADO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."UBICACION_ESTAMPADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."UBICACION_ESTAMPADO" ADD CONSTRAINT "PK_UBICACION_ESTAMPADO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METODO_PAGO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."METODO_PAGO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."METODO_PAGO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."METODO_PAGO" ADD CONSTRAINT "PK_METODO_PAGO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table METODO_ENVIO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."METODO_ENVIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."METODO_ENVIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."METODO_ENVIO" ADD CONSTRAINT "PK_METODO_ENVIO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TALLA_CAMISETA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."TALLA_CAMISETA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TALLA_CAMISETA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TALLA_CAMISETA" ADD CONSTRAINT "PK_TALLA_CAMISETA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAMANO_ESTAMPADO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."TAMANO_ESTAMPADO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TAMANO_ESTAMPADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."TAMANO_ESTAMPADO" ADD CONSTRAINT "PK_TAMANO_ESTAMPADO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."USUARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."USUARIO" MODIFY ("PERSONA" NOT NULL ENABLE);
  ALTER TABLE "ESTAMPATE_DB"."USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAMISETA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "FK_CAMISETA_CARRITO_COMPRAS" FOREIGN KEY ("CARRITO")
	  REFERENCES "ESTAMPATE_DB"."CARRITO_COMPRAS" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "FK_CAMISETA_COLOR_CAMISETA" FOREIGN KEY ("COLOR")
	  REFERENCES "ESTAMPATE_DB"."COLOR_CAMISETA" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "FK_CAMISETA_ESTAMPA" FOREIGN KEY ("ESTAMPA")
	  REFERENCES "ESTAMPATE_DB"."ESTAMPA" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "FK_CAMISETA_MATERIAL_CAMISETA" FOREIGN KEY ("MATERIAL")
	  REFERENCES "ESTAMPATE_DB"."MATERIAL_CAMISETA" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "FK_CAMISETA_TALLA_CAMISETA" FOREIGN KEY ("TALLA")
	  REFERENCES "ESTAMPATE_DB"."TALLA_CAMISETA" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "FK_CAMISETA_TAMANO_ESTAMPADO" FOREIGN KEY ("TAMANO_ESTAMPADO")
	  REFERENCES "ESTAMPATE_DB"."TAMANO_ESTAMPADO" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD CONSTRAINT "FK_CAMISETA_UBICACION_ESTAM_01" FOREIGN KEY ("UBICACION_ESTAMPADO")
	  REFERENCES "ESTAMPATE_DB"."UBICACION_ESTAMPADO" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."CAMISETA" ADD FOREIGN KEY ("TIPO_CAMISETA")
	  REFERENCES "ESTAMPATE_DB"."TIPO_CAMISETA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARRITO_COMPRAS
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."CARRITO_COMPRAS" ADD CONSTRAINT "FK_CARRITO_COMPRAS_USUARIO" FOREIGN KEY ("USUARIO")
	  REFERENCES "ESTAMPATE_DB"."USUARIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTAMPA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" ADD CONSTRAINT "FK_ESTAMPA_TEMA" FOREIGN KEY ("TEMA")
	  REFERENCES "ESTAMPATE_DB"."TEMA" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."ESTAMPA" ADD CONSTRAINT "FK_ESTAMPA_USUARIO" FOREIGN KEY ("USUARIO")
	  REFERENCES "ESTAMPATE_DB"."USUARIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROL_PRIVILEGIO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."ROL_PRIVILEGIO" ADD CONSTRAINT "FK_ROL_PRIVILEGIO_PRIVILEGIO" FOREIGN KEY ("ID_PRIVILEGIO")
	  REFERENCES "ESTAMPATE_DB"."PRIVILEGIO" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."ROL_PRIVILEGIO" ADD CONSTRAINT "FK_ROL_PRIVILEGIO_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "ESTAMPATE_DB"."ROL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."USUARIO" ADD CONSTRAINT "FK_USUARIO_PERSONA" FOREIGN KEY ("PERSONA")
	  REFERENCES "ESTAMPATE_DB"."PERSONA" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."USUARIO" ADD FOREIGN KEY ("ROL")
	  REFERENCES "ESTAMPATE_DB"."ROL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO_REDSOCIAL
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."USUARIO_REDSOCIAL" ADD CONSTRAINT "FK_REDSOCIAL" FOREIGN KEY ("ID_REDSOCIAL")
	  REFERENCES "ESTAMPATE_DB"."RED_SOCIAL" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."USUARIO_REDSOCIAL" ADD CONSTRAINT "FK_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ESTAMPATE_DB"."USUARIO" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "ESTAMPATE_DB"."VENTA" ADD CONSTRAINT "FK_VENTA_CARRITO_COMPRAS" FOREIGN KEY ("CARRITO")
	  REFERENCES "ESTAMPATE_DB"."CARRITO_COMPRAS" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."VENTA" ADD CONSTRAINT "FK_VENTA_METODO_ENVIO" FOREIGN KEY ("METODO_ENVIO")
	  REFERENCES "ESTAMPATE_DB"."METODO_ENVIO" ("ID") ENABLE;
  ALTER TABLE "ESTAMPATE_DB"."VENTA" ADD CONSTRAINT "FK_VENTA_METODO_PAGO" FOREIGN KEY ("METODO_PAGO")
	  REFERENCES "ESTAMPATE_DB"."METODO_PAGO" ("ID") ENABLE;
